// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
// eslint-disable-next-line @typescript-eslint/no-require-imports
const { FlatCompat } = require("@eslint/eslintrc");
// eslint-disable-next-line @typescript-eslint/no-require-imports
const js = require("@eslint/js");

const compat = new FlatCompat({
  baseDirectory: __dirname,
  recommendedConfig: js.configs.recommended,
});

module.exports = [
  ...compat.extends("./.eslintrc.json"),
  {
    // import/order uses a removed ESLint v10 API; disabled until eslint-plugin-import-x migration
    rules: { "import/order": "off" },
  },
  {
    ignores: ["*.js", "*.d.ts", "node_modules/", "*.generated.ts", "coverage/"],
  },
];