import { GitHub } from "projen/lib/github";
import { NodePackageManager, NodeProject } from "projen/lib/javascript";
import { synthSnapshot } from "projen/lib/util/synth";
import { describe, expect, it } from "vitest";
import { PullRequestCoverageComment } from "./pull-request-comment";
import { PullRequestLabeler } from "./pull-request-labeler";

const makeProject = (packageManager: NodePackageManager) =>
	new NodeProject({
		name: "test",
		defaultReleaseBranch: "main",
		packageManager,
	});

describe("PullRequestCoverageComment", () => {
	describe("vitest runner (default)", () => {
		it("uses npx vitest for YARN_BERRY", () => {
			const project = makeProject(NodePackageManager.YARN_BERRY);
			new PullRequestCoverageComment(project.github ?? new GitHub(project));
			const config =
				synthSnapshot(project)[".github/workflows/pull-request.yml"];
			expect(config).toEqual(
				`# ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".

name: pull-request
on:
  pull_request: {}
jobs:
  coverage-comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      CI: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: \${{ github.event.pull_request.head.ref }}
          repository: \${{ github.event.pull_request.head.repo.full_name }}
      - name: Install dependencies
        run: yarn install --check-files
      - name: Run tests
        run: npx vitest run --coverage
      - name: Coverage Comment
        uses: MishaKav/jest-coverage-comment@v1
concurrency:
  group: \${{ github.workflow }}-\${{ github.event.pull_request.number }}
  cancel-in-progress: true
`,
			);
		});

		it("uses npx vitest for NPM", () => {
			const project = makeProject(NodePackageManager.NPM);
			new PullRequestCoverageComment(project.github ?? new GitHub(project));
			const config =
				synthSnapshot(project)[".github/workflows/pull-request.yml"];
			expect(config).toContain("run: npx vitest run --coverage");
		});

		it("uses npx vitest for PNPM", () => {
			const project = makeProject(NodePackageManager.PNPM);
			new PullRequestCoverageComment(project.github ?? new GitHub(project));
			const config =
				synthSnapshot(project)[".github/workflows/pull-request.yml"];
			expect(config).toContain("run: npx vitest run --coverage");
		});

		it("adds bun setup step and uses bunx vitest for BUN", () => {
			const project = makeProject(NodePackageManager.BUN);
			new PullRequestCoverageComment(project.github ?? new GitHub(project));
			const config =
				synthSnapshot(project)[".github/workflows/pull-request.yml"];
			expect(config).toEqual(
				`# ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".

name: pull-request
on:
  pull_request: {}
jobs:
  coverage-comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      CI: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: \${{ github.event.pull_request.head.ref }}
          repository: \${{ github.event.pull_request.head.repo.full_name }}
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Run tests
        run: bunx vitest run --coverage
      - name: Coverage Comment
        uses: MishaKav/jest-coverage-comment@v1
concurrency:
  group: \${{ github.workflow }}-\${{ github.event.pull_request.number }}
  cancel-in-progress: true
`,
			);
		});
	});

	describe("jest runner", () => {
		it("uses npx jest for NPM", () => {
			const project = makeProject(NodePackageManager.NPM);
			new PullRequestCoverageComment(project.github ?? new GitHub(project), {
				testRunner: "jest",
			});
			const config =
				synthSnapshot(project)[".github/workflows/pull-request.yml"];
			expect(config).toContain(
				"run: npx jest --coverage --coverageReporters json-summary",
			);
		});

		it("adds bun setup step and uses bunx jest for BUN", () => {
			const project = makeProject(NodePackageManager.BUN);
			new PullRequestCoverageComment(project.github ?? new GitHub(project), {
				testRunner: "jest",
			});
			const config =
				synthSnapshot(project)[".github/workflows/pull-request.yml"];
			expect(config).toContain("uses: oven-sh/setup-bun@v2");
			expect(config).toContain(
				"run: bunx jest --coverage --coverageReporters json-summary",
			);
		});
	});

	describe("concurrency", () => {
		it("adds a per-PR concurrency group", () => {
			const project = makeProject(NodePackageManager.BUN);
			new PullRequestCoverageComment(project.github ?? new GitHub(project));
			const config =
				synthSnapshot(project)[".github/workflows/pull-request.yml"];
			expect(config).toContain(
				"group: ${{ github.workflow }}-${{ github.event.pull_request.number }}",
			);
			expect(config).toContain("cancel-in-progress: true");
		});
	});

	describe("shared workflow", () => {
		it("merges coverage-comment and triage into a single pull-request.yml", () => {
			const project = makeProject(NodePackageManager.BUN);
			const github = project.github ?? new GitHub(project);
			new PullRequestCoverageComment(github);
			new PullRequestLabeler(github);

			const snapshot = synthSnapshot(project);
			expect(snapshot[".github/workflows/pull-request.yml"]).toBeDefined();
			expect(
				snapshot[".github/workflows/pull-request-comment.yml"],
			).toBeUndefined();
			expect(
				snapshot[".github/workflows/pull-request-labeler.yml"],
			).toBeUndefined();

			const config = snapshot[".github/workflows/pull-request.yml"];
			expect(config).toContain("coverage-comment:");
			expect(config).toContain("triage:");
		});

		it("sets up the trigger only once when both components are used", () => {
			const project = makeProject(NodePackageManager.BUN);
			const github = project.github ?? new GitHub(project);
			new PullRequestCoverageComment(github);
			new PullRequestLabeler(github);

			const config =
				synthSnapshot(project)[".github/workflows/pull-request.yml"];
			const triggerCount = (config.match(/pull_request:/g) ?? []).length;
			expect(triggerCount).toBe(1);
		});
	});
});
