import { PullRequestLabeler } from "@thoroc/github-actions/pull-request-labeler";
import { Project } from "projen";
import { GitHub } from "projen/lib/github";
import { synthSnapshot } from "projen/lib/util/synth";

describe("pull-request-labeler", () => {
	it("Adds a new github workflow", () => {
		// Arrange
		const project = new Project({
			name: "test",
		});
		const github = new GitHub(project);
		new PullRequestLabeler(github);

		// Act
		const snapshot = synthSnapshot(project);
		const config = snapshot[".github/workflows/pull-request-labeler.yml"];

		// Assert
		expect(
			config,
		).toEqual(`# ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".

name: pull-request-labeler
on:
  pull_request_target: {}
jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/labeler@v5
        with:
          dot: true
`);
	});

	it("Adds a labeler config", () => {
		// Arrange
		const project = new Project({
			name: "test",
		});
		const github = new GitHub(project);
		new PullRequestLabeler(github);

		// Act
		const snapshot = synthSnapshot(project);
		const config = snapshot[".github/labeler.yml"];

		// Assert
		expect(
			config,
		).toEqual(`# ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".

documentation:
  - "*.md"
githubAction:
  - .github/**
component:
  - src/components/**
test:
  - test/**/*.test.ts
`);
	});
});
