import { GitHub } from "projen/lib/github";
import { NodePackageManager, NodeProject } from "projen/lib/javascript";
import { synthSnapshot } from "projen/lib/util/synth";
import { PullRequestJestCoverageComment } from "../../../src/components/github-actions/pull-request-comment";

describe("pull-request-comment", () => {
  it("Adds a new github workflow with YARN", () => {
    // Arrange
    const project = new NodeProject({
      name: "test",
      defaultReleaseBranch: "main",
      packageManager: NodePackageManager.YARN_BERRY,
    });
    const github = project.github ?? new GitHub(project);
    new PullRequestJestCoverageComment(github);

    // Act
    const snapshot = synthSnapshot(project);
    const config = snapshot[".github/workflows/pull-request-comment.yml"];

    // Assert
    expect(config).toEqual(`# ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".

name: pull-request-comment
on:
  pull_request: {}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      CI: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: \${{ github.event.pull_request.head.ref }}
          repository: \${{ github.event.pull_request.head.repo.full_name }}
      - name: Install dependencies
        run: yarn install --check-files
      - name: Run tests
        run: npx jest --coverage --coverageReporters json-summary
      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
`);
  });

  it("Adds a new github workflow with NPM", () => {
    // Arrange
    const project = new NodeProject({
      name: "test",
      defaultReleaseBranch: "main",
      packageManager: NodePackageManager.NPM,
    });
    const github = project.github ?? new GitHub(project);
    new PullRequestJestCoverageComment(github);

    // Act
    const snapshot = synthSnapshot(project);
    const config = snapshot[".github/workflows/pull-request-comment.yml"];

    // Assert
    expect(config).toEqual(`# ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".

name: pull-request-comment
on:
  pull_request: {}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      CI: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: \${{ github.event.pull_request.head.ref }}
          repository: \${{ github.event.pull_request.head.repo.full_name }}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npx jest --coverage --coverageReporters json-summary
      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
`);
  });
});
