import { Project } from "projen";
import { GitHub } from "projen/lib/github";
import { synthSnapshot } from "projen/lib/util/synth";
import { describe, expect, it } from "vitest";
import { PullRequestLabeler } from "./pull-request-labeler";

describe("pull-request-labeler", () => {
	it("adds jobs to the shared pull-request workflow", () => {
		const project = new Project({ name: "test" });
		const github = new GitHub(project);
		new PullRequestLabeler(github);

		const snapshot = synthSnapshot(project);
		const config = snapshot[".github/workflows/pull-request.yml"];

		expect(config).toEqual(
			`# ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".

name: pull-request
on:
  pull_request: {}
jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/labeler@v5
        with:
          dot: true
concurrency:
  group: \${{ github.workflow }}-\${{ github.event.pull_request.number }}
  cancel-in-progress: true
`,
		);
	});

	it("does not create a pull-request-labeler.yml workflow", () => {
		const project = new Project({ name: "test" });
		const github = new GitHub(project);
		new PullRequestLabeler(github);

		const snapshot = synthSnapshot(project);
		expect(
			snapshot[".github/workflows/pull-request-labeler.yml"],
		).toBeUndefined();
	});

	it("adds a per-PR concurrency group", () => {
		const project = new Project({ name: "test" });
		const github = new GitHub(project);
		new PullRequestLabeler(github);

		const config =
			synthSnapshot(project)[".github/workflows/pull-request.yml"];
		expect(config).toContain(
			"group: ${{ github.workflow }}-${{ github.event.pull_request.number }}",
		);
		expect(config).toContain("cancel-in-progress: true");
	});

	it("adds a labeler config", () => {
		const project = new Project({ name: "test" });
		const github = new GitHub(project);
		new PullRequestLabeler(github);

		const config = synthSnapshot(project)[".github/labeler.yml"];

		expect(config).toEqual(
			`# ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".

documentation:
  - changed-files:
      - any-glob-to-any-file: "*.md"
githubAction:
  - changed-files:
      - any-glob-to-any-file: .github/**
component:
  - changed-files:
      - any-glob-to-any-file: src/components/**
test:
  - changed-files:
      - any-glob-to-any-file: src/**/*.test.ts
`,
		);
	});
});
