import { Project } from "projen";
import { GitHub } from "projen/lib/github";
import { synthSnapshot } from "projen/lib/util/synth";
import { describe, expect, it } from "vitest";
import { ReleasePlease } from "./release-please";

describe("ReleasePlease", () => {
	it("adds a release-please workflow with defaults", () => {
		// Arrange
		const project = new Project({ name: "test" });
		const github = new GitHub(project);
		new ReleasePlease(github);

		// Act
		const snapshot = synthSnapshot(project);
		const config = snapshot[".github/workflows/release-please.yml"];

		// Assert
		expect(
			config,
		).toEqual(`# ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".

name: release-please
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: \${{ secrets.GITHUB_TOKEN }}
          release-type: node
`);
	});

	it("supports a custom release type", () => {
		// Arrange
		const project = new Project({ name: "test" });
		const github = new GitHub(project);
		new ReleasePlease(github, { releaseType: "python" });

		// Act
		const snapshot = synthSnapshot(project);
		const config = snapshot[".github/workflows/release-please.yml"];

		// Assert
		expect(config).toContain("release-type: python");
	});

	it("supports a custom target branch", () => {
		// Arrange
		const project = new Project({ name: "test" });
		const github = new GitHub(project);
		new ReleasePlease(github, { targetBranch: "master" });

		// Act
		const snapshot = synthSnapshot(project);
		const config = snapshot[".github/workflows/release-please.yml"];

		// Assert
		expect(config).toContain("- master");
	});

	it("supports a config file", () => {
		// Arrange
		const project = new Project({ name: "test" });
		const github = new GitHub(project);
		new ReleasePlease(github, { configFile: "release-please-config.json" });

		// Act
		const snapshot = synthSnapshot(project);
		const config = snapshot[".github/workflows/release-please.yml"];

		// Assert
		expect(config).toContain("config-file: release-please-config.json");
	});

	it("supports a manifest file", () => {
		// Arrange
		const project = new Project({ name: "test" });
		const github = new GitHub(project);
		new ReleasePlease(github, {
			manifestFile: ".release-please-manifest.json",
		});

		// Act
		const snapshot = synthSnapshot(project);
		const config = snapshot[".github/workflows/release-please.yml"];

		// Assert
		expect(config).toContain("manifest-file: .release-please-manifest.json");
	});

	it("supports include-component-in-tag", () => {
		// Arrange
		const project = new Project({ name: "test" });
		const github = new GitHub(project);
		new ReleasePlease(github, { includeComponentInTag: true });

		// Act
		const snapshot = synthSnapshot(project);
		const config = snapshot[".github/workflows/release-please.yml"];

		// Assert
		expect(config).toContain("include-component-in-tag: true");
	});

	it("supports include-v-in-tag", () => {
		// Arrange
		const project = new Project({ name: "test" });
		const github = new GitHub(project);
		new ReleasePlease(github, { includeVInTag: false });

		// Act
		const snapshot = synthSnapshot(project);
		const config = snapshot[".github/workflows/release-please.yml"];

		// Assert
		expect(config).toContain("include-v-in-tag: false");
	});

	it("supports skip-github-release", () => {
		// Arrange
		const project = new Project({ name: "test" });
		const github = new GitHub(project);
		new ReleasePlease(github, { skipGithubRelease: true });

		// Act
		const snapshot = synthSnapshot(project);
		const config = snapshot[".github/workflows/release-please.yml"];

		// Assert
		expect(config).toContain("skip-github-release: true");
	});

	it("supports skip-github-pull-request", () => {
		// Arrange
		const project = new Project({ name: "test" });
		const github = new GitHub(project);
		new ReleasePlease(github, { skipGithubPullRequest: true });

		// Act
		const snapshot = synthSnapshot(project);
		const config = snapshot[".github/workflows/release-please.yml"];

		// Assert
		expect(config).toContain("skip-github-pull-request: true");
	});

	it("supports a component name", () => {
		// Arrange
		const project = new Project({ name: "test" });
		const github = new GitHub(project);
		new ReleasePlease(github, { component: "my-package" });

		// Act
		const snapshot = synthSnapshot(project);
		const config = snapshot[".github/workflows/release-please.yml"];

		// Assert
		expect(config).toContain("component: my-package");
	});

	it("supports a custom pull-request title pattern", () => {
		// Arrange
		const project = new Project({ name: "test" });
		const github = new GitHub(project);
		new ReleasePlease(github, {
			pullRequestTitlePattern: "chore: release ${version}",
		});

		// Act
		const snapshot = synthSnapshot(project);
		const config = snapshot[".github/workflows/release-please.yml"];

		// Assert
		expect(config).toContain(
			'pull-request-title-pattern: "chore: release ${version}"',
		);
	});

	it("supports bump-minor-pre-major", () => {
		// Arrange
		const project = new Project({ name: "test" });
		const github = new GitHub(project);
		new ReleasePlease(github, { bumpMinorPreMajor: true });

		// Act
		const snapshot = synthSnapshot(project);
		const config = snapshot[".github/workflows/release-please.yml"];

		// Assert
		expect(config).toContain("bump-minor-pre-major: true");
	});

	it("supports bump-patch-for-minor-pre-major", () => {
		// Arrange
		const project = new Project({ name: "test" });
		const github = new GitHub(project);
		new ReleasePlease(github, { bumpPatchForMinorPreMajor: true });

		// Act
		const snapshot = synthSnapshot(project);
		const config = snapshot[".github/workflows/release-please.yml"];

		// Assert
		expect(config).toContain("bump-patch-for-minor-pre-major: true");
	});
});
