import { Project } from "projen";
import { GitHub } from "projen/lib/github";
import { synthSnapshot } from "projen/lib/util/synth";
import { describe, expect, it } from "vitest";
import { ReleasePlease } from "./release-please";

describe("release-please", () => {
	it("Adds a new github workflow with defaults", () => {
		// Arrange
		const project = new Project({
			name: "test",
		});
		const github = new GitHub(project);
		new ReleasePlease(github);

		// Act
		const snapshot = synthSnapshot(project);
		const config = snapshot[".github/workflows/release-please.yml"];

		// Assert
		expect(
			config,
		).toEqual(`# ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".

name: release-please
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: \${{ secrets.GITHUB_TOKEN }}
          release-type: node
`);
	});

	it("Supports a custom release type", () => {
		// Arrange
		const project = new Project({
			name: "test",
		});
		const github = new GitHub(project);
		new ReleasePlease(github, { releaseType: "python" });

		// Act
		const snapshot = synthSnapshot(project);
		const config = snapshot[".github/workflows/release-please.yml"];

		// Assert
		expect(config).toContain("release-type: python");
	});

	it("Supports a custom target branch", () => {
		// Arrange
		const project = new Project({
			name: "test",
		});
		const github = new GitHub(project);
		new ReleasePlease(github, { targetBranch: "master" });

		// Act
		const snapshot = synthSnapshot(project);
		const config = snapshot[".github/workflows/release-please.yml"];

		// Assert
		expect(config).toContain("- master");
	});
});
