import { synthSnapshot } from "projen/lib/util/synth";
import { GitHooksEnabledProject } from "../../../src";
import { GitHooksManagerType } from "../../../src/components/githooksmanager";

describe("Lefthook", () => {
  it("has a config file", () => {
    // Arrange
    const project = new GitHooksEnabledProject({
      name: "test",
      defaultReleaseBranch: "main",
      prettier: true,
      gitHooksManager: GitHooksManagerType.LEFTHOOK,
    });

    // Act
    const snapshot = synthSnapshot(project);
    const config = snapshot["lefthook.yml"];

    // Assert
    expect(config).toEqual(`# ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".

- actionName: pre-commit
  commands:
    - name: prettier
      glob: "*.md"
      run: npx prettier --write --prose-wrap always
    - name: eslint
      glob: src/**/*.{ts,tsx}
      run: eslint --cache --fix
    - name: prettier
      glob: src/**/*.{ts,tsx}
      run: prettier --write
`);
  });
});
