import { Project } from "projen";
import { GitHub } from "projen/lib/github";
import { synthSnapshot } from "projen/lib/util/synth";
import { AutoMerge } from "../../../src/components/github-actions/auto-merge";

describe("auto-merge", () => {
  it("Adds a new github workflow", () => {
    // Arrange
    const project = new Project({
      name: "test",
    });
    const github = new GitHub(project);
    new AutoMerge(github);

    // Act
    const snapshot = synthSnapshot(project);
    const config = snapshot[".github/workflows/auto-merge.yml"];

    // Assert
    expect(config).toEqual(`# ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".

name: auto-merge
on:
  pull_request:
    branches:
      - main
jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    if: \${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.9.1
        with:
          github-token: \${{ secrets.GITHUB_TOKEN }}
`);
  });
});
