import { GitHub } from "projen/lib/github";
import { Project } from "projen/lib/project";
import { synthSnapshot } from "projen/lib/util/synth";
import { CloseStaleIssue } from "../../../src/components/github-actions/close-stale-issue";

describe("close-stale-issue", () => {
  it("Adds a new github workflow", () => {
    // Arrange
    const project = new Project({ name: "test" });
    const github = new GitHub(project);
    new CloseStaleIssue(github);

    // Act
    const snapshot = synthSnapshot(project);
    const config = snapshot[".github/workflows/close-stale-issue.yml"];

    // Assert
    expect(config).toEqual(`# ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".

name: close-stale-issue
on:
  workflow_dispatch:
    schedule:
      cron: 0 */4 * * *
jobs:
  cleanup:
    name: stale issue job
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
      pull-requests: write
    steps:
      - uses: aws-actions/stale-issue-cleanup@v3
        with:
          stale-issue-message: This issue has not received a response in a while. If you want to keep this issue open, please leave a comment below and auto-close will be canceled.
          ancient-issue-message: This issue has not received any attention in 1 year. If you want to keep this issue open, please leave a comment below and auto-close will be canceled.
          stale-pr-message: This PR has not received a response in a while. If you want to keep this issue open, please leave a comment below and auto-close will be canceled.
          ancient-pr-message: This PR has not received any attention in 1 year. If you want to keep this issue open, please leave a comment below and auto-close will be canceled.
          stale-issue-label: closing-soon
          exempt-issue-labels: awaiting-approval
          stale-pr-label: no-pr-activity
          exempt-pr-labels: awaiting-approval
          response-requested-label: response-requested
          closed-for-staleness-label: closed-for-staleness
          days-before-stale: 4
          days-before-close: 7
          days-before-ancient: 365
          minimum-upvotes-to-exempt: 5
          loglevel: DEBUG
          dry-run: true
          repo-token: \${{ secrets.GITHUB_TOKEN }}
`);
  });
});
